name: Vulnerability check

on:
  schedule:
    - cron: '0 7 * * 1'  # Weekly on Mondays at 7:00 AM

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Vulncheck
        run: just vulncheck
